version: "2.1"

networks:
  test-network:

services:
  node-service:
    build:
      context: ../
      dockerfile: ./Dockerfile
    environment:
      #OVERWIRTE .env file
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - test-network
