version: "2.1"

networks:
  test-network:

services:
  node-service:
    build:
      context: ../
      dockerfile: ./Dockerfile.dev
    environment:
    env_file:
      - .env
    # command: yarn watch #overwrite command
    container_name: node-service
    volumes:
      - ./src:/app/src
      - ./dist:/app/dist
      - ./conf:/app/conf
    ports:
      - 8080:8080
      - 9229:9229
    networks:
      - test-network
