FROM node:11.9.0-alpine

WORKDIR /app

COPY .babelrc        .babelrc
COPY .prettierrc     .prettierrc
COPY package.json    package.json
COPY .eslintrc.json  .eslintrc.json


RUN npm install
RUN npm dedupe

CMD ["yarn", "watch"]